name: Scheduled Merge Remote Action
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop               # set the branch to merge to
          fetch-depth: 0 
      
      - name: Merge Upstream
        uses: ethan42/merge-upstream@v4
        with:
          upstream: nervosnetwork/ckb                                  # set the upstream repo manually
          upstream-branch: develop    # set the upstream branch to merge from
          branch: develop             # set the branch to merge to
